# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
