# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180416_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message_html',
        ),
    ]
